package com.linkalma.utils;

public class ApplicationConstants {

	public static final String  MSG = "";
	public static int USER_ROLE_CTGRY_CODE = 1;
	public static int SCHOOL_DATA_CTGRY_CODE = 2;
	public static int SCHOOL_UPDATES_CTGRY_CODE = 3;

	
	public static String GET_ALL_SCHOOLS_QUERY = "SELECT * FROM SCHOOL WHERE APPROVED = 'Y' AND ACTIVEYN = 'Y' ORDER BY CREATEDTTM DESC";
	
	public static String VALIDATE_USER_QUERY ="SELECT U.USERID,U.ROLEID,U.EMAILADDRESS "
			+ " FROM USER U, USERCREDENTIALS  C, STATICCODES S "
			+ " WHERE U.EMAILADDRESS = ? AND C.PASSWORD = ? AND U.USERID = C.USERID "
			+ " AND U.ROLEID = S.CODE AND S.CATEGORYID = 1";

	public static String VALIDATE_SCHOOL_QUERY ="SELECT S.SchoolID, S.SchoolName, S.LinkAlmaURL, S.EmailAddress, SC.SCHOOLID, SC.PASSWORD "
			+ " FROM SCHOOL S, SCHOOLCREDENTIALS SC "
			+ " WHERE S.SCHOOLID = SC.SCHOOLID AND S.EmailAddress = ? AND SC.PASSWORD = ?";
	
	public static String GET_ALL_SCHOOLS_BY_USERID_QUERY = "SELECT US.USERID, S.SCHOOLID, US.USERSCHOOLID, "
			+ "US.FROMYEAR, TOYEAR, US.PASSOUTBATCH, S.SCHOOLNAME, S.ADDRESS1, S.BRANCH "
			+ "FROM USERSCHOOL US, SCHOOL S "
			+ "WHERE US.SCHOOLID = S.SCHOOLID "
			+ "AND USERID = ? "
			+ "AND APPROVED = 'Y' AND ACTIVEYN = 'Y'";
	
	public static String INSERT_SCHOOL_QUERY = "INSERT INTO SCHOOL (SCHOOLNAME, ADDRESS1, ADDRESS2, BRANCH,"
		 		+ "EMAILADDRESS, WEBSITEURL, LINKALMAURL, APPROVED, ACTIVEYN, CREATEDTTM, UPDATEDTTM, CREATEUSERID, UPDATEUSERID) "
	      		+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static String INSERT_WALLPOST_QUERY = "INSERT INTO USERUPDATES "
			+ " (USERID, SUBJECT, DESCRIPTION, UPLOADEDON, CREATEUSERID, UPDATEUSERID) "
			+ " VALUES (?, ?, ?, ?, ?, ?);";

	public static String INSER_USER_CREDENTIALS_QUERY = "INSERT INTO USERCREDENTIALS (USERID,PASSWORD) "
      		+ "VALUES (?, ?)";
	
	public static String INSER_SCHOOL_CREDENTIALS_QUERY = "INSERT INTO SCHOOLCREDENTIALS (USERID,PASSWORD) "
      		+ "VALUES (?, ?)";

	public static String INSERT_USER_QUERY = "INSERT INTO USER (FIRSTNAME, MIDDLENAME, LASTNAME, ADDRESS1, ADDRESS2, PHONE1, "
		+ "PHONE2, PHONE3, PHONE4, GENDER, CITY, STATE, COUNTRY, EMAILADDRESS, DOB, ABOUTME, PHOTO, APPROVED, "
		+ "CREATEDTTM, UPDATEDTTM) "
		+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public static String INSERT_USER_SCHOOL_QUERY = "INSERT INTO USERSCHOOL "
			+ "(USERID, SCHOOLID, FROMYEAR, TOYEAR, PASSOUTBATCH, CREATEUSERID) "
      		+ "VALUES (?, ?, ?, ?, ?, ?)";

	public static String DELETE_USER_SCHOOL = "DELETE FROM USERSCHOOL WHERE USERSCHOOLID = ?";
	
	public static String GET_SCHOOL_NEWS_FOR_USERSCHOOL = "SELECT US.USERID, US.SCHOOLID, SN.ID as NEWSID, SN.NEWSDESCRIPTION, "
			+ " SN.NEWSTYPE, S.SCHOOLNAME, S.BRANCH, S.EMAILADDRESS, S.LINKALMAURL "
			+ " FROM USERSCHOOL US, SCHOOLNEWS SN, SCHOOL S "
			+ " WHERE US.SCHOOLID = SN.SCHOOLID AND S.SCHOOLID = SN.SCHOOLID "
			+ " AND S.APPROVED = 'Y' AND S.ACTIVEYN = 'Y' AND US.USERID = ?";
	
	public static String GET_SCHOOL_UPDATES_FOR_USERSCHOOL = 
			 "SELECT SUP.SCHOOLUPDATESID, US.USERID, US.SCHOOLID, SUP.TITLE, SUP.DESCRIPTION, SUP.TYPE, "
			 + " SUP.CREATEDTTM ,S.SCHOOLNAME, S.BRANCH, S.EMAILADDRESS, S.LINKALMAURL "
			 + " FROM USERSCHOOL US, SCHOOLUPDATES SUP, SCHOOL S "
			 + " WHERE US.SCHOOLID = SUP.SCHOOLID "
			 + " AND SUP.SCHOOLID = S.SCHOOLID "
			 + " AND S.APPROVED = 'Y' "
			 + " AND S.ACTIVEYN = 'Y' "
			 + " AND US.SCHOOLID = ?";
	
	public static String GET_USER_WALL_POSTS = "SELECT UU.POSTID, UU.USERID, UU.SUBJECT, UU.DESCRIPTION, "
			+ " UU.CREATEDTTM, U.FIRSTNAME, U.LASTNAME "
			+ " FROM USERUPDATES UU, USER U "
			+ " WHERE UU.USERID = U.USERID"
			+ " AND U.USERID = ?"
			+ " ORDER BY UU.CREATEDTTM DESC" ;
	
	public static String UPDATE_USER_PROFILE_PERSONAL_DETAILS = 
			" UPDATE user SET FirstName = ?,    MiddleName = ?,    LastName = ?, "
			+ " Address1 = ?, Address2 = ?, CountryCode = ?, Phone1 = ?, Phone2 = ?, Phone3 = ?, Phone4 = ?, "
			+ " Gender = ?, City = ?, State = ?, Country = ?, "
			+ " EmailAddress = ?, DOB = ?, AboutMe = ?, "
			+ " UpdateDttm = CURRENT_TIMESTAMP "
			+ " WHERE UserID = ?";
	
	public static String SELECT_USER_DETAILS = 
			" SELECT U.UserID, UC.PASSWORD, RoleID, SC.PrimaryDecode as Role, FirstName, MiddleName, LastName, Address1, Address2, "
			+ " CountryCode, Phone1, Phone2, Phone3, Phone4, Gender, City, State, Country, EmailAddress, DOB, "
			+ " AboutMe, Photo, Approved, ActiveYN, CreateDttm, UpdateDttm "
			+ " FROM user U , USERCREDENTIALS UC, STATICCODES SC "
			+ " WHERE U.USERID = UC.USERID"
			+ " AND U.ROLEID = SC.CODE AND SC.CATEGORYID = 1 "	// CATEGORY_CD = 1 defines Roles
			+ " AND U.USERID = ?";
	
	public static String UPDATE_USER_CREDENTIALS = 
			" UPDATE USERCREDENTIALS SET PASSWORD = ?"
			+ " WHERE USERID = ?";
	
	public static String UPDATE_USER_SCHOOL_DETAILS = 
			" UPDATE USERSCHOOL "
			+ " SET SCHOOLID=?, FROMYEAR=?, TOYEAR=?, "
			+ " PASSOUTBATCH=?, UPDATEUSERID=?, UPDATEDTTM=CURRENT_TIMESTAMP "
			+ " WHERE USERSCHOOLID=?";
	
	public static String GET_SCHOOL_BY_EMAILID =
			" SELECT SCHOOLID, SCHOOLNAME, ADDRESS1, ADDRESS2, BRANCH, EMAILADDRESS, "
			+ " WEBSITEURL, LINKALMAURL, ACTIVEYN, APPROVED, CREATEDTTM "
			+ " FROM SCHOOL "
			+ " WHERE EMAILADDRESS = ? "
			+ " and APPROVED = 'Y' "
			+ " AND ACTIVEYN = 'Y'";
	
	public static String GET_USER_WORKPLACE_DETAILS = "SELECT W.USERWORKPLACEID, U.USERID, W.ORGANISATIONNAME, W.FROMMONTH, "
			+ " W.FROMYEAR, W.TOMONTH, W.TOYEAR, W.DESIGNATION, W.DESCRIPTION "
			+ " FROM USER U, USERWORKPLACE W "
			+ " WHERE U.USERID = W.USERID"
			+ " AND U.USERID = ?";
	
	public static String GET_SCHOOLNEWS = " SELECT SCHOOLID, NEWSDESCRIPTION, NEWSTYPE "
			+ " FROM SCHOOLNEWS "
			+ " WHERE SCHOOLID = ? AND NEWSTYPE = ?";
	
	public static String INSERT_SCHOOL_UPDATES = "INSERT INTO SCHOOLUPDATES (SCHOOLID,TITLE,DESCRIPTION,TYPE,CREATEUSERID,UPDATEUSERID) "
			+ " VALUES(?, ?, ?, ?, ?, ?)";
	
	public static String INSERT_SCHOOL_DATA = 
			"INSERT INTO SCHOOLDATA (SCHOOLID, TYPE, DOCUMENTNAME, TITLE, DESCRIPTION, GRADE, DIVISION, "
			+ " CREATEUSERID, UPDATEUSERID)"
			+ " VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static String GET_SCHOOL_CURRICULUM_DATA = "SELECT S.SCHOOLID, SD.ID, S.SCHOOLNAME, SD.TITLE, CODES.PRIMARYDECODE AS TYPE , CODES.CODE AS UPDATETYPE, "
			+ " SD.GRADE,SD.DIVISION, SD.DESCRIPTION, SD.DOCUMENTNAME, SD.CREATEDTTM"
			+ " FROM SCHOOL S, SCHOOLDATA SD, STATICCODES CODES "
			+ " WHERE S.SCHOOLID = SD.SCHOOLID AND CODES.CODE = SD.TYPE AND SD.SCHOOLID = ? AND CODES.CATEGORYID = ? "
			+ " ORDER BY SD.ID, SD.CREATEDTTM";
	
	public static String GET_SCHOOL_UPDATES = "SELECT SU.SCHOOLID, SU.SCHOOLUPDATESID, S.SCHOOLNAME, SU.TITLE, "
			+ " CODES.PRIMARYDECODE AS TYPE, SU.DESCRIPTION, SU.CREATEDTTM, CODES.CODE AS UPDATETYPE"
			+ " FROM SCHOOL S, SCHOOLUPDATES SU, STATICCODES CODES "
			+ " WHERE S.SCHOOLID = SU.SCHOOLID AND CODES.CODE = SU.TYPE AND SU.SCHOOLID = ? AND CODES.CODE = ? AND CODES.CATEGORYID = "+SCHOOL_UPDATES_CTGRY_CODE;

	public static String GET_STATIC_CODES_FOR_CATEGORY_ID = "SELECT CATEGORYID, CODE, PRIMARYDECODE, SECONDARYDECODE "
			+ " FROM STATICCODES "
			+ " WHERE CATEGORYID = ? ORDER BY CODE";

	public static String GET_SCHOOL_ALL_UPDATES = "SELECT SU.SCHOOLID, SU.SCHOOLUPDATESID, S.SCHOOLNAME, SU.TITLE, "
			+ " CODES.PRIMARYDECODE AS TYPE, SU.DESCRIPTION, SU.CREATEDTTM, CODES.CODE AS UPDATETYPE "
			+ " FROM SCHOOL S, SCHOOLUPDATES SU, STATICCODES CODES "
			+ " WHERE S.SCHOOLID = SU.SCHOOLID "
			+ " AND CODES.CODE = SU.TYPE "
			+ " AND SU.SCHOOLID = ? "
			+ " AND CODES.CATEGORYID = "+SCHOOL_UPDATES_CTGRY_CODE
			+ " ORDER BY SU.SCHOOLID,CODES.CODE , SU.CREATEDTTM DESC";

	public static String UPDATE_SUCCESS_MSG = "Data Saved Successfully";
	
	public static String SCHOOL_INNER_PAGE_EVENTS = "EVENTS";
	public static String SCHOOL_INNER_PAGE_CURRICULUM = "CURRICULUM";
	public static String SCHOOL_INNER_PAGE_ABOUTUS = "ABOUTUS";
	public static String SCHOOL_INNER_PAGE_GALLERY = "GALLERY";
}

