package com.linkalma.utils;

public class ApplicationConstants {

	public static final String  MSG = "";
	
	public static String GET_ALL_SCHOOLS_QUERY = "SELECT * FROM SCHOOL WHERE APPROVED = 'Y' AND ACTIVEYN = 'Y' ORDER BY CREATEDTTM DESC";
	
	public static String GET_ALL_SCHOOLS_BY_USERID_QUERY = "SELECT US.USERID, S.SCHOOLID, US.USERSCHOOLID, "
			+ "US.FROMYEAR, TOYEAR, US.PASSOUTBATCH, S.SCHOOLNAME, S.ADDRESS1, S.BRANCH "
			+ "FROM USERSCHOOL US, SCHOOL S "
			+ "WHERE US.SCHOOLID = S.SCHOOLID "
			+ "AND USERID = 1 "
			+ "AND APPROVED = 'Y' AND ACTIVEYN = 'Y'";
	
	public static String INSERT_SCHOOL_QUERY = "INSERT INTO SCHOOL (SCHOOLNAME, ADDRESS1, ADDRESS2, BRANCH,"
		 		+ "EMAILADDRESS, WEBSITEURL, LINKALMAURL, APPROVED, ACTIVEYN, CREATEDTTM, UPDATEDTTM, CREATEUSERID, UPDATEUSERID) "
	      		+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static String INSER_CREDENTIALS_QUERY = "INSERT INTO CREDENTIALS (USERID,PASSWORD) "
      		+ "VALUES (?, ?)";
	
	public static String INSERT_USER_QUERY = "INSERT INTO USER (FIRSTNAME, MIDDLENAME, LASTNAME, ADDRESS1, ADDRESS2, PHONE1, "
		+ "PHONE2, PHONE3, PHONE4, GENDER, CITY, STATE, COUNTRY, EMAILADDRESS, DOB, ABOUTME, PHOTO, APPROVED, "
		+ "CREATEDTTM, UPDATEDTTM) "
		+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public static String INSERT_USER_SCHOOL_QUERY = "INSERT INTO USERSCHOOL "
			+ "(USERID, SCHOOLID, FROMYEAR, TOYEAR, PASSOUTBATCH, BRANCH, CREATEUSERID) "
      		+ "VALUES (?, ?, ?, ?, ?, ?, ?)";

	public static String DELETE_USER_SCHOOL = "DELETE FROM USERSCHOOL WHERE USERSCHOOLID = ?";
}
